export enum LinksEnum {
  HOME = "/",
  NEWS = "/news",
  NOTICE = "/notice",
  NOTICES = "/notices",
  NOTICES_SELL = NOTICES + "/sell",
  NOTICES_IN_GOOD_HANDS = NOTICES + "/in-good-hands",
  NOTICES_LOST_FOUND = NOTICES + "/lost-found",
  NOTICES_FAVORITE = NOTICES + "/favorites",
  NOTICES_OWN = NOTICES + "/own",
  FRIENDS = "/sponsors",
  LOGIN = "/login",
  REGISTER = "/register",
  USER = "/profile",
  ADD_PET = "/add-pet",
  ADD_PET_CATEGORY = LinksEnum.ADD_PET + "/category",
  ADD_PET_DETAILS = LinksEnum.ADD_PET + "/details",
  ADD_PET_INFO = LinksEnum.ADD_PET + "/info",
}
